// Pure helpers for vendoring Orchis primitives. No I/O here, so the transform is unit tested.
import { createHash } from "node:crypto";

export const SOURCE_REPO = "learningtofail/Orchis-Desktop-Design-System";

/**
 * Upstream files and how each is reduced to primitives (decision 4: type, spacing, color ladder, elevation;
 * no GNOME chrome, no dark surface semantics). `cutBefore` keeps everything above the marker line.
 * @type {ReadonlyArray<{ path: string, stripImports?: boolean, cutBefore?: string }>}
 */
export const SOURCE_FILES = [
  { path: "tokens/fonts.css", stripImports: true },
  { path: "tokens/colors.css", cutBefore: "/* ── Accent ── */" },
  { path: "tokens/typography.css" },
  { path: "tokens/spacing.css" },
  { path: "tokens/radius.css" },
  { path: "tokens/elevation.css" },
  { path: "tokens/motion.css" },
];

/** @param {string} text */
export const sha256 = (text) => createHash("sha256").update(text).digest("hex");

/**
 * @param {string} text Upstream file content.
 * @param {{ stripImports?: boolean, cutBefore?: string }} rule
 * @returns {string}
 */
export function reduceFile(text, rule) {
  let out = text;
  if (rule.stripImports) out = out.replace(/^@import .*;\n/gm, "");
  if (rule.cutBefore) {
    const at = out.indexOf(rule.cutBefore);
    if (at === -1) throw new Error(`Marker not found upstream: ${rule.cutBefore}`);
    out = `${out.slice(0, at).trimEnd()}\n}\n`;
  }
  return out;
}

/**
 * Builds the vendored stylesheet from the upstream file contents.
 * @param {string} sha Upstream commit the files were read at.
 * @param {Record<string, string>} contents Upstream path to file text.
 * @returns {string}
 */
export function buildVendored(sha, contents) {
  const header = [
    "/* VENDORED, DO NOT EDIT. Generated by `npm run tokens:sync` from",
    `   ${SOURCE_REPO} at ${sha}.`,
    "   Primitives only: palette and grey ladder, type scale, spacing, radii, elevation, motion, font-family",
    "   strings. The upstream Google Fonts @import and the dark GNOME surface tokens are omitted on purpose.",
    "   Site decisions belong in site.tokens.css. `npm run tokens:check` fails when this file drifts. */",
    "",
  ].join("\n");
  const parts = SOURCE_FILES.map((rule) => {
    const text = contents[rule.path];
    if (typeof text !== "string") throw new Error(`Missing upstream file: ${rule.path}`);
    return `/* ---- ${rule.path} ---- */\n${reduceFile(text, rule)}`;
  });
  return `${header}\n${parts.join("\n")}`;
}
